#!/usr/bin/env python3
"""Generate Kokoro narration in semantic chunks and replace fallback timing with measured audio timing."""
from __future__ import annotations
from pathlib import Path
import argparse, json, sys
import numpy as np
import soundfile as sf

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'scripts'))
import build_manifest as bm
SR=24000

def synthesize(pipeline,text:str,voice:str,speed:float)->np.ndarray:
    if not text.strip(): return np.zeros(0,dtype=np.float32)
    pieces=[]
    for result in pipeline(text,voice=voice,speed=speed):
        if hasattr(result,'output'):
            audio=result.output
        elif isinstance(result,(tuple,list)) and len(result)>=3:
            audio=result[2]
        else:
            raise RuntimeError(f'Unexpected Kokoro result type: {type(result)!r}')
        arr=np.asarray(audio,dtype=np.float32).reshape(-1)
        if len(arr): pieces.append(arr)
    if not pieces: raise RuntimeError(f'Kokoro returned no audio for: {text[:100]!r}')
    return np.concatenate(pieces)

def write_ts(manifest):
    js=json.dumps(manifest,ensure_ascii=False,indent=2)
    (ROOT/'src/generatedManifest.ts').write_text("// AUTO-GENERATED by scripts/generate_audio.py — exact measured narration timings.\nimport type {SceneSpec} from './types';\n"+f"export const scenes: SceneSpec[] = {js} as SceneSpec[];\n"+"export const TOTAL_DURATION = scenes.reduce((m,s)=>Math.max(m,s.start+s.duration),0);\n",encoding='utf-8')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--chapter',type=int,choices=range(1,11)); ap.add_argument('--voice',default='af_heart'); ap.add_argument('--speed',type=float,default=1.0); ap.add_argument('--silence',type=float,default=0.06)
    args=ap.parse_args()
    try:
        from kokoro import KPipeline
    except Exception as e:
        raise SystemExit('Kokoro is not installed. Run: pip install kokoro soundfile numpy\n'+str(e))
    scenes=bm.make_estimated_manifest(); audio_dir=ROOT/'public/audio'; audio_dir.mkdir(parents=True,exist_ok=True); pipeline=KPipeline(lang_code='a')
    selected=[s for s in scenes if args.chapter is None or s['module']==args.chapter]
    print(f'Generating {len(selected)} scenes using voice={args.voice} speed={args.speed}')
    exact_by_id={}
    for scene in selected:
        cursor=0.0; full=[]; exact_segments=[]
        for seg in scene['segments']:
            if seg.get('silent'):
                seconds=max(0.0,float(seg['end'])-float(seg['start'])); audio=np.zeros(int(round(seconds*SR)),dtype=np.float32)
            else:
                audio=synthesize(pipeline,seg.get('tts') or seg['text'],args.voice,args.speed)
            start=cursor; end=cursor+len(audio)/SR; e={**seg,'start':round(start,4),'end':round(end,4)}; exact_segments.append(e); full.append(audio); cursor=end
            if not seg.get('silent') and args.silence>0:
                gap=np.zeros(int(round(args.silence*SR)),dtype=np.float32); full.append(gap); cursor+=len(gap)/SR; exact_segments[-1]['end']=round(cursor,4)
        if exact_segments and args.silence>0 and full and len(full[-1])==int(round(args.silence*SR)):
            full.pop(); cursor-=args.silence; exact_segments[-1]['end']=round(cursor,4)
        wav=np.concatenate(full) if full else np.zeros(1,dtype=np.float32); out=audio_dir/f'scene_{scene["id"]:02d}.wav'; sf.write(out,wav,SR,subtype='PCM_16')
        if exact_segments: exact_segments[-1]['end']=round(cursor,4)
        exact_by_id[scene['id']]={**scene,'duration':round(cursor,4),'segments':exact_segments}; print(f'  scene {scene["id"]:02d}: {cursor:7.2f}s -> {out.name}')
    merged=[]; cursor=0.0
    for scene in scenes:
        s=exact_by_id.get(scene['id'],scene); s={**s,'start':round(cursor,4)}; merged.append(s); cursor+=float(s['duration'])
    write_ts(merged)
    (ROOT/'public/audio/generation.json').write_text(json.dumps({'voice':args.voice,'speed':args.speed,'sampleRate':SR,'chapter':args.chapter,'generatedSceneIds':[s['id'] for s in selected]},indent=2),encoding='utf-8')
    print(f'Manifest updated. Current total duration: {cursor/60:.2f} min')
if __name__=='__main__': main()
