import React from 'react';
import {AbsoluteFill, Easing, interpolate, useCurrentFrame, useVideoConfig} from 'remotion';
import type {SceneSpec, SegmentSpec, VisualKey} from './types';

const clamp=(v:number,a=0,b=1)=>Math.max(a,Math.min(b,v));
const fade=(frame:number,start:number,fps:number)=>interpolate(frame,[start*fps,(start+.32)*fps],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.16,1,.3,1)});
const palette={bg:'#07111f',panel:'#102642',cyan:'#4be1ff',green:'#7cf29a',yellow:'#ffd166',red:'#ff6b6b',muted:'#9fb1c8',white:'#f6f9ff',blue:'#2e85c7'};

const EquationCard:React.FC<{text:string;opacity?:number}>=({text,opacity=1})=><div style={{position:'absolute',left:280,right:280,top:390,padding:'34px 46px',borderRadius:28,background:'rgba(12,35,62,.94)',border:`2px solid ${palette.cyan}66`,fontSize:74,fontWeight:900,textAlign:'center',color:palette.green,opacity,boxShadow:'0 24px 80px #0007'}}>{text}</div>;
const Box=({x,y,label='x',scale=1}:{x:number;y:number;label?:string;scale?:number})=><div style={{position:'absolute',left:x,top:y,width:190,height:145,border:`7px solid ${palette.yellow}`,borderRadius:22,display:'grid',placeItems:'center',fontSize:78,fontWeight:900,color:palette.yellow,boxShadow:`0 0 42px ${palette.yellow}22`,scale}}>{label}</div>;
const Jersey=({x,y=320}:{x:number;y?:number})=><div style={{position:'absolute',left:x,top:y,width:150,height:190,background:palette.blue,clipPath:'polygon(25% 0,40% 12%,60% 12%,75% 0,100% 20%,82% 45%,72% 35%,72% 100%,28% 100%,28% 35%,18% 45%,0 20%)',filter:'drop-shadow(0 18px 24px #0008)'}}/>;
const Balance=({tilt=0,left='x + 7',right='19'}:{tilt?:number;left?:string;right?:string})=><div style={{position:'absolute',left:410,top:235,width:1100,height:440}}><div style={{position:'absolute',left:545,top:120,width:12,height:290,background:palette.muted}}/><div style={{position:'absolute',left:185,top:165,width:730,height:10,background:palette.cyan,borderRadius:10,rotate:`${tilt}deg`}}/><div style={{position:'absolute',left:120,top:250,width:270,height:95,border:`6px solid ${palette.muted}`,borderTop:'none',borderRadius:'0 0 150px 150px',display:'grid',placeItems:'center',fontSize:46,fontWeight:800}}>{left}</div><div style={{position:'absolute',right:120,top:250,width:270,height:95,border:`6px solid ${palette.muted}`,borderTop:'none',borderRadius:'0 0 150px 150px',display:'grid',placeItems:'center',fontSize:46,fontWeight:800}}>{right}</div></div>;
const Graph=({labels=false}:{labels?:boolean})=><svg style={{position:'absolute',left:520,top:220,width:900,height:520}} viewBox="0 0 900 520">{Array.from({length:9},(_,i)=><line key={`v${i}`} x1={80+i*90} y1="40" x2={80+i*90} y2="450" stroke="#ffffff13" strokeWidth="2"/>)}{Array.from({length:6},(_,i)=><line key={`h${i}`} x1="80" y1={450-i*75} x2="820" y2={450-i*75} stroke="#ffffff13" strokeWidth="2"/>)}<line x1="80" y1="450" x2="840" y2="450" stroke={palette.muted} strokeWidth="5"/><line x1="80" y1="470" x2="80" y2="35" stroke={palette.muted} strokeWidth="5"/><line x1="130" y1="410" x2="790" y2="90" stroke={palette.cyan} strokeWidth="10" strokeLinecap="round"/><circle cx="310" cy="323" r="12" fill={palette.green}/><circle cx="550" cy="207" r="12" fill={palette.green}/>{labels?<><text x="600" y="150" fill={palette.yellow} fontSize="42" fontWeight="800">m = rate</text><text x="95" y="412" fill={palette.yellow} fontSize="42" fontWeight="800">b = start</text></>:null}</svg>;
const Fruit=({mixed=false}:{mixed?:boolean})=><div>{Array.from({length:8},(_,i)=><div key={i} style={{position:'absolute',left:390+(i%4)*280,top:300+Math.floor(i/4)*210,width:118,height:118,borderRadius:'50%',background:(!mixed||i<5)?'#e84f4f':'#ff9f1a',boxShadow:'inset -18px -22px 35px #0003,0 18px 35px #0005'}}><div style={{position:'absolute',left:54,top:-25,width:12,height:35,background:'#7d5b38',rotate:'12deg'}}/></div>)}</div>;
const TeamVisual=()=> <div>{[0,1,2].map((n)=><div key={n} style={{position:'absolute',left:430+n*380,top:280,textAlign:'center'}}><div style={{width:110,height:110,borderRadius:'50%',background:palette.cyan,margin:'0 auto 18px',boxShadow:`0 0 38px ${palette.cyan}44`}}/><div style={{width:160,height:210,background:palette.blue,borderRadius:26}}/><div style={{fontSize:34,marginTop:18,color:palette.yellow}}>2 balls + 1 cone</div></div>)}</div>;
const FractionVisual=()=> <div style={{position:'absolute',left:770,top:270,width:360,height:360,border:`10px solid ${palette.cyan}`,borderRadius:'50%',overflow:'hidden',boxShadow:`0 0 55px ${palette.cyan}22`}}><div style={{position:'absolute',left:0,top:175,width:360,height:10,background:palette.cyan}}/><div style={{position:'absolute',left:175,top:0,width:10,height:360,background:palette.cyan}}/><div style={{position:'absolute',left:0,top:0,width:180,height:180,background:`${palette.green}33`}}/></div>;
const WordsToMath=()=> <><div style={{position:'absolute',left:250,top:330,width:480,height:210,borderRadius:34,background:palette.panel,display:'grid',placeItems:'center',fontSize:68,fontWeight:900}}>WORDS</div><div style={{position:'absolute',left:890,top:390,fontSize:94,color:palette.cyan}}>→</div><div style={{position:'absolute',right:250,top:330,width:480,height:210,borderRadius:34,background:palette.panel,display:'grid',placeItems:'center',fontSize:62,fontWeight:900,color:palette.green}}>EQUATION</div></>;
const Workflow=()=> <div style={{position:'absolute',left:180,right:180,top:330,display:'flex',gap:28}}>{['REPRESENT','SIMPLIFY','SOLVE','CHECK'].map((x,i)=><React.Fragment key={x}><div style={{flex:1,padding:'48px 22px',borderRadius:26,background:i===3?`${palette.green}22`:palette.panel,border:`2px solid ${i===3?palette.green:palette.cyan}44`,fontSize:42,fontWeight:900,textAlign:'center'}}>{x}</div>{i<3?<div style={{fontSize:62,color:palette.cyan,alignSelf:'center'}}>→</div>:null}</React.Fragment>)}</div>;
const Cricket=()=> <div style={{position:'absolute',left:520,top:230,width:880,height:500,borderRadius:'50%',background:'#2c7848',border:'12px solid #d7efda',boxShadow:'0 25px 70px #0008'}}><div style={{position:'absolute',left:410,top:85,width:60,height:330,background:'#cfa86c',borderRadius:30}}/><div style={{position:'absolute',left:425,top:80,width:30,height:340,borderLeft:'4px dashed white',borderRight:'4px dashed white'}}/><div style={{position:'absolute',left:90,top:225,width:32,height:32,borderRadius:'50%',background:palette.yellow}}/><div style={{position:'absolute',right:100,top:210,width:32,height:32,borderRadius:'50%',background:palette.cyan}}/></div>;

const genericVisual=(key:VisualKey,scene:SceneSpec,seg:SegmentSpec,sceneProgress:number,frame:number,fps:number)=>{
  const pulse=1+Math.sin(frame/12)*.018;
  switch(key){
    case 'chapter': return <div style={{position:'absolute',left:150,top:240,right:160}}><div style={{fontSize:28,letterSpacing:5,color:palette.cyan,fontWeight:800}}>MODULE {scene.module}</div><div style={{fontSize:94,lineHeight:.98,fontWeight:950,marginTop:24,maxWidth:1450}}>{scene.title.replace(/^\d+\.\s*/,'')}</div><div style={{fontSize:38,color:palette.muted,marginTop:38,maxWidth:1380,lineHeight:1.35}}>{scene.concept}</div></div>;
    case 'box': return <><Box x={855} y={300} scale={pulse}/><div style={{position:'absolute',left:590,top:360,fontSize:86,color:palette.cyan}}>→</div><div style={{position:'absolute',left:1200,top:360,fontSize:86,color:palette.cyan}}>→</div></>;
    case 'three-boxes': return <><Box x={530} y={320}/><Box x={850} y={320}/><Box x={1170} y={320}/><EquationCard text="3x = ₹150"/></>;
    case 'tickets': return <div style={{position:'absolute',left:400,right:400,top:300,display:'flex',gap:35}}>{Array.from({length:5},(_,i)=><div key={i} style={{flex:1,height:210,border:`5px dashed ${palette.yellow}`,borderRadius:22,display:'grid',placeItems:'center',fontSize:54,fontWeight:900}}>x</div>)}</div>;
    case 'bat': return <><div style={{position:'absolute',left:700,top:270,width:80,height:410,borderRadius:'45px 45px 30px 30px',background:'#d39b55',rotate:'-15deg'}}/><div style={{position:'absolute',left:1080,top:270,width:80,height:410,borderRadius:'45px 45px 30px 30px',background:'#d39b55',rotate:'15deg'}}/><EquationCard text={scene.practice}/></>;
    case 'jerseys': return <>{[0,1,2,3].map((n)=><Jersey key={n} x={430+n*280}/>)}</>;
    case 'expression-parts': return <div style={{position:'absolute',left:420,right:420,top:300,textAlign:'center'}}><div style={{fontSize:110,fontWeight:950}}><span style={{color:palette.yellow}}>350</span><span style={{color:palette.cyan}}>x</span> <span style={{color:palette.white}}>+</span> <span style={{color:palette.green}}>500</span></div><div style={{display:'flex',justifyContent:'space-around',fontSize:34,marginTop:45}}><span style={{color:palette.yellow}}>coefficient</span><span style={{color:palette.cyan}}>variable</span><span style={{color:palette.green}}>constant</span></div></div>;
    case 'bill': return <div style={{position:'absolute',left:700,top:225,width:520,height:530,background:'#f7f1df',color:'#172231',borderRadius:18,padding:'50px',boxShadow:'0 30px 70px #0008'}}><div style={{fontSize:46,fontWeight:900,borderBottom:'3px dashed #7d8792',paddingBottom:24}}>A BILL IS A STORY</div><div style={{fontSize:38,lineHeight:1.8,marginTop:30}}>Base amount<br/>× quantity<br/>+ fixed fee<br/><b>= total pattern</b></div></div>;
    case 'taxi': return <><div style={{position:'absolute',left:560,top:350,fontSize:180}}>🚕</div><EquationCard text="₹60 + ₹14k"/></>;
    case 'shirts': return <>{[0,1,2].map((n)=><Jersey key={n} x={580+n*330}/>)}</>;
    case 'fruit': return <Fruit/>; case 'fruit-mixed': return <Fruit mixed/>; case 'like-terms': case 'combine': return <EquationCard text={scene.kind==='practice'?scene.practice:'3x + 5x = 8x'}/>;
    case 'scale': return <Balance/>; case 'balance-operation': return <Balance left="x + 7 − 7" right="19 − 7"/>; case 'inverse': return <><Balance/><div style={{position:'absolute',left:720,top:720,fontSize:44,color:palette.yellow}}>same operation on both sides</div></>;
    case 'teams': return <TeamVisual/>; case 'brackets': case 'distribute': return <><TeamVisual/><EquationCard text="3(x + 4) = 3x + 12"/></>; case 'fraction': return <FractionVisual/>; case 'words-to-math': return <WordsToMath/>;
    case 'money': return <><div style={{position:'absolute',left:560,top:300,fontSize:150}}>₹</div><div style={{position:'absolute',right:500,top:320,fontSize:86,fontWeight:900,color:palette.green}}>x − 250 = 750</div></>; case 'fees': return <EquationCard text="3x + 500 = 3500"/>;
    case 'cost-graph': case 'graph': return <Graph/>; case 'graph-labels': return <Graph labels/>; case 'cricket': return <Cricket/>; case 'shop': return <><div style={{position:'absolute',left:440,top:300,fontSize:160}}>🏪</div><EquationCard text="275x + 150 = 1800"/></>; case 'workflow': return <Workflow/>;
    case 'countdown': {const remaining=Math.max(0,Math.ceil(20-(frame/fps-seg.start))); return <div style={{position:'absolute',inset:0,display:'grid',placeItems:'center'}}><div style={{width:330,height:330,borderRadius:'50%',border:`14px solid ${palette.cyan}`,display:'grid',placeItems:'center',fontSize:118,fontWeight:950,color:palette.yellow}}>{remaining}</div><div style={{position:'absolute',top:690,fontSize:40,color:palette.muted}}>Solve it yourself — no narration</div></div>}
    case 'answer': return <div style={{position:'absolute',left:230,right:230,top:310,textAlign:'center'}}><div style={{fontSize:56,color:palette.green,fontWeight:900}}>✓ CHECK YOUR ANSWER</div><div style={{fontSize:70,fontWeight:950,marginTop:40,lineHeight:1.25}}>{scene.answer}</div></div>;
    case 'mistake': return <div style={{position:'absolute',left:260,right:260,top:300,padding:'50px 70px',borderRadius:34,background:`${palette.red}13`,border:`3px solid ${palette.red}77`}}><div style={{fontSize:50,color:palette.red,fontWeight:950}}>✕ COMMON MISTAKE</div><div style={{fontSize:48,lineHeight:1.3,marginTop:32}}>{scene.mistake}</div></div>;
    case 'steps': return <div style={{position:'absolute',left:180,right:180,top:330,display:'flex',alignItems:'center',gap:22}}>{scene.steps.map((s,i)=><React.Fragment key={s}><div style={{flex:1,padding:'42px 28px',borderRadius:28,background:i<=Math.floor(sceneProgress*3)?palette.panel:'#0b1728',border:`2px solid ${i<=Math.floor(sceneProgress*3)?palette.cyan+'66':'#ffffff12'}`,fontSize:44,fontWeight:850,textAlign:'center'}}>{s}</div>{i<scene.steps.length-1?<div style={{fontSize:54,color:palette.cyan}}>→</div>:null}</React.Fragment>)}</div>;
    case 'practice': return <div style={{position:'absolute',left:210,right:210,top:290,textAlign:'center'}}><div style={{fontSize:30,letterSpacing:4,color:palette.yellow,fontWeight:900}}>YOUR TURN</div><div style={{fontSize:66,lineHeight:1.2,fontWeight:950,marginTop:28}}>{scene.practice}</div></div>;
    case 'questions': return <div style={{position:'absolute',left:250,right:250,top:300,display:'flex',gap:28}}>{['WHAT DO I KNOW?','WHAT DON’T I KNOW?','HOW ARE THEY CONNECTED?'].map(x=><div key={x} style={{flex:1,padding:'65px 30px',borderRadius:28,background:palette.panel,fontSize:38,fontWeight:900,textAlign:'center'}}>{x}</div>)}</div>;
    case 'rule': return <div style={{position:'absolute',left:230,right:230,top:280}}><div style={{fontSize:32,letterSpacing:5,color:palette.cyan,fontWeight:900}}>THE RULE</div><div style={{fontSize:66,lineHeight:1.2,fontWeight:950,marginTop:28}}>{scene.rule}</div><div style={{fontSize:38,lineHeight:1.35,color:palette.muted,marginTop:40}}>{scene.example}</div></div>;
    case 'equation': return <EquationCard text={seg.text.length<90?seg.text:scene.example}/>; case 'check': return <Workflow/>; default: return <div style={{position:'absolute',left:260,right:260,top:300,fontSize:62,lineHeight:1.22,fontWeight:900,textAlign:'center'}}>{scene.concept}</div>;
  }
};

export const SemanticScene:React.FC<{scene:SceneSpec}>=({scene})=>{
  const frame=useCurrentFrame(); const {fps}=useVideoConfig(); const time=frame/fps;
  const seg=scene.segments.find((s)=>time>=s.start&&time<s.end) ?? scene.segments[scene.segments.length-1] ?? {start:0,end:scene.duration,text:'',visual:'concept' as const};
  const segOpacity=fade(frame,seg.start,fps); const sceneProgress=clamp(time/Math.max(.001,scene.duration));
  return <AbsoluteFill style={{background:'radial-gradient(circle at 50% 38%,#102a4a 0,#07111f 58%,#040912 100%)',color:palette.white,fontFamily:'Inter, Arial, sans-serif',overflow:'hidden'}}><div style={{position:'absolute',inset:0,backgroundImage:'linear-gradient(#ffffff08 1px,transparent 1px),linear-gradient(90deg,#ffffff08 1px,transparent 1px)',backgroundSize:'72px 72px'}}/><div style={{position:'absolute',left:72,top:48,fontSize:22,letterSpacing:4,color:palette.muted}}>ALGEBRA • ZERO TO CONFIDENCE</div><div style={{position:'absolute',right:72,top:44,padding:'11px 20px',borderRadius:999,background:'#ffffff0b',fontSize:22,color:palette.cyan}}>MODULE {scene.module} • {scene.label.toUpperCase()}</div><div style={{opacity:segOpacity}}>{genericVisual(seg.visual,scene,seg,sceneProgress,frame,fps)}</div>{seg.text ? <div style={{position:'absolute',left:150,right:150,bottom:78,padding:'18px 28px',borderRadius:22,background:'#02060bcc',fontSize:34,fontWeight:650,lineHeight:1.28,textAlign:'center',opacity:segOpacity}}>{seg.text}</div>:null}<div style={{position:'absolute',left:0,bottom:0,height:8,width:`${sceneProgress*100}%`,background:palette.cyan}}/><div style={{position:'absolute',right:44,bottom:26,fontSize:19,color:palette.muted}}>Scene {scene.id}/60</div></AbsoluteFill>;
};
